name: Deploy

on:
  push:
    branches: main
    paths:
      - "src/**"
      - "index.html"
      - "package.json"
      - "tsconfig.json"
      - "vite.config.js"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo VITE_SEATGEEK_CLIENT_ID=${{ secrets.SEATGEEK_CLIENT_ID }} >> .env
          echo VITE_SEATGEEK_CLIENT_SECRET=${{ secrets.SEATGEEK_CLIENT_SECRET }} >> .env

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
